language: node_js
node_js: "node"
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
services:
  - mongodb
script:
  - npm run lint
  - npm test
after_success: npm run coverage