version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - ./data:/data/db
  app:
    container_name: chatapptest
    restart: always
    build: .
    ports:
      - "7205:7202"
    links:
      - mongo
    environment:
      - NODE_ENV=production
