version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo
    expose:
      - "27017"
    volumes:
      - ./data:/data/db
  app:
    container_name: chatapp
    image: chatapp:test
    restart: "no"
    build: .
    ports:
      - "80:7205"
    links:
      - mongo
    environment:
      - NODE_ENV=production